### ISSUE TITLE
Export HOTOSM tool

### ISSUE THREAD

**Issue by ramyaragupathy** [ramyaragupathy/hotosm-viz#10]
Referencing #7, [HOTOSM's export tool](https://export.hotosm.org/en/v3/) is another option to download OpenStreetMap data. While playing around with the interface, looks like the tool can deal with any rectangular/custom polygon boundaries. Using this ticket to document learnings.

- [YAML](https://github.com/ramyaragupathy/hotosm-viz/issues/10#issuecomment-378567010)
- [From Network](https://github.com/ramyaragupathy/hotosm-viz/issues/10#issuecomment-379433052)
- [Creating Export](https://github.com/hotosm/osm-export-tool/wiki/Export-Tool-API#create-an-export)

**Comment by ramyaragupathy** [comment]
### YAML
- It is a data serialisation language like JSON. Emphasis is on readability
- Written in plain text with certain syntax formatting
- Different from markdown. Full form: _YAML Ain't Markup Language_
- _.yml_ & _.yaml_ extensions
- Space indentation defines scopes
- date & time in ISO 8601 standard yyyy-mm-ddThh:mm:ss
- Data represented as k-v pairs
- There also lists, comments, type conversions, anchoring specific keys & anchoring k-v pairs.
- Resources
  - [Ultimate Guide](https://learnxinyminutes.com/docs/yaml/)
  - [Cheat Sheet](https://lzone.de/cheat-sheet/YAML)
  - [YAML-JSON](https://medium.com/@kenichishibata/yaml-to-json-cheatsheet-c3ac3ef519b8)


Eg:

```yaml
buildings: 
  select: 
    - name
    - building
  types: 
    - polygons
  where: "building IS NOT NULL"
hospitals: 
  select: 
    - name
    - amenity
  where: "amenity = hospital"
waterways: 
  select: 
    - name
    - waterway
  types: 
    - lines
    - polygons
  where: "natural IN ('waterway')"

```
This is equivalent to:

```json
{buildings:{select:[name, building], types:[polygons], where:"building IS NOT NULL"},
hospitals:{select:[name, amenity], where:"amenity=hospital"},
waterways:{select:[name, watrway], types:[lines, polygons], where:"natural IN ('waterway')"}
```
